[Controller] POST /users - Postman Test (Error Found) ★Error★ java.lang.IllegalStateException: No primary or single unique constructor ★Solution★ Figuring it out ... ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ Error Log ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ /* Postman */ {     "timestamp": "2023-10-18T03:58:09.842+00:00",     "status": 500,     "error": "Internal Server Error",     "path": "/users" } /* Server */ 2023-10-18T12:52:32.985+09:00 ERROR 13720 --- [p-nio-80-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.IllegalStateException: No primary or single unique constructor found for class com.pro.mini.vo.UserVO] with root cause
java.lang.IllegalStateException: No primary or single unique constructor found for class com.pro.mini.vo.UserVO
■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■