[Controller] POST /users - Postman Test ★Error★ org.hibernate.PropertyValueException: not-null property references a null or transient value ★Solution★ Figuring it out ... ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ Error Log ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ /* Postman */ {     "timestamp": "2023-10-18T04:08:59.089+00:00",     "status": 500,     "error": "Internal Server Error",     "path": "/users" } /* Server */ 2023-10-18T13:08:59.030+09:00  INFO 22456 --- [p-nio-80-exec-1] com.pro.mini.controller.UserController   : [UserController] saveUseruserVO ::: com.pro.mini.vo.UserVO@12846885 2023-10-18T13:08:59.038+09:00  INFO 22456 --- [p-nio-80-exec-1] com.pro.mini.service.UserService         : [UserService] saveUseruserVO ::: com.pro.mini.vo.UserVO@12846885 2023-10-18T13:08:59.072+09:00 ERROR 22456 --- [p-nio-80-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.dao.DataIntegrityViolationException: not-null property references a null or transient value : com.pro.mini.vo.UserVO.email] with root cause
org.hibernate.PropertyValueException: not-null property references a null or transient value : com.pro.mini.vo.UserVO.email
■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■