[Controller] POST /users - json Parsing (Mapping) Error ★Error★ jsonStr wasn't converted to the userVO ... ★Solution★ @JsonIgnoreProperties ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ Error Log ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ /* Server */ 2023-10-18T15:56:34.349+09:00  INFO 30040 --- [p-nio-80-exec-1] com.pro.mini.controller.UserController   : jsonStr ::: {     "name": "test_user",     "phone": "010-0000-0000",     "email": "test_user@gmail.com" } 2023-10-18T15:56:34.390+09:00  INFO 30040 --- [p-nio-80-exec-1] com.pro.mini.controller.UserController   : [saveUser]	userVO ::: UserVO(id = 0, name = null, phone = null, email = null, createdAt = null, tempYn = null) 2023-10-18T15:56:34.402+09:00  INFO 30040 --- [p-nio-80-exec-1] com.pro.mini.service.UserService         : [saveUser]	userVO ::: UserVO(id = 0, name = null, phone = null, email = null, createdAt = null, tempYn = null) 2023-10-18T15:56:34.440+09:00 ERROR 30040 --- [p-nio-80-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.dao.DataIntegrityViolationException: not-null property references a null or transient value : com.pro.mini.vo.UserVO.email] with root cause
org.hibernate.PropertyValueException: not-null property references a null or transient value : com.pro.mini.vo.UserVO.email
■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■